<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/3/12
 * Time: 14:05
 */
namespace app\admin\controller;
use app\admin\model\ClassifyModel;
use app\admin\Traits\Whole;
use think\Controller;
class Classify extends Controller{
    use Whole{
        isUser as public;
        isOutInsider as public;
    }
    /**
     * @var $model
     * 公共模型
     */
    protected $model;
    /**
     * @var $data
     * 用户信息
     */
    protected $data;
    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try{
            self::isUser();
            self::isOutInsider();
            $data = Whole::dataInfo();
            $this->model = new ClassifyModel( $data );
            $this->data = $data;
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }

    /**
     * @return ClassifyModel
     * @throws \Exception
     */
    public function model(){
        return new ClassifyModel( Whole::dataInfo() );
    }

    /**
     * @return mixed
     * 分类列表
     */
    public function Classify(){
        try{
            $this->model = $this->model();
            $Classify = $this->model->Classify();
            $page = $Classify['data']->render();
            return view('Classify',[
	            'Classify'  =>  $Classify,
	            'page'  =>  $page
            ]);
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }
    /**
     * @return \think\response\Json
     * 添加分类
     */
    public function addClassify(){
        try{
            $this->model = $this->model();
            if(Request()->isPost()){
                $data = input('post.');
                $this->model->addClassify($data);
            }
        }catch (\Exception $e){
            return json_decode($e->getMessage(),true);
        }
        return view('addClassify');
    }
    /**
     * @return mixed|\think\response\Json
     * 编辑分类
     */
    public function editClassify(){
        try{
            $this->model = $this->model();
            if(Request()->isPost()){
                $data = input('post.');
                $this->model->editClassify($data);
            }
            $id = input('get.id');
            $classify = $this->model->infoClassify($id);
            return view('editClassify',[
            	'classify'  =>  $classify
            ]);
        }catch (\Exception $e){
            return json_decode( $e->getMessage() ,true);
        }
    }
    /**
     * @return \think\response\Json
     * 修改分类状态
     */
    public function is_show(){
        try{
            $this->model = $this->model();
            if(Request()->isGet()){
                $data = input('get.');
                $this->model->is_show($data);
            }
        }catch (\Exception $e){
            return json_decode( $e->getMessage() ,true);
        }
    }
    /**
     * @return \think\response\Json
     * 删除分类
     */
    public function is_del(){
        try{
            $this->model = $this->model();
            if(Request()->isGet()){
                $data = input('get.');
                $this->model->is_del($data);
            }
        }catch (\Exception $e){
            return json_decode( $e->getMessage() , true);
        }
    }
}