<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/2/26
 * Time: 10:55
 */
namespace app\admin\controller;
use app\admin\Traits\Whole;
use think\Controller;
class Index extends Controller
{
    use Whole{
        isUser as public;
        isOutInsider as public;
    }
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        self::isUser();
        self::isOutInsider();
    }

    /**
     * @return mixed
     * 主页
     */
    public function Index(){
        $data = Whole::dataInfo();
        if(empty($data)){    //检查是否登录
            $this->redirect('User/login');
        }
        return view('index',[
        	'data'  =>  $data
        ]);
    }
}