<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/5/8
 * Time: 10:36
 */
namespace app\admin\controller;

use app\admin\model\NoteModel;
use app\admin\model\NoticeModel;
use app\admin\Traits\Whole;
use function PHPSTORM_META\type;
use think\Controller;
use think\Request;

class Notice extends Controller{
	/**
	 * 公告管理器
	 */

	/**
	 * @var $data
	 * 用户资料
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = Whole::dataInfo();
			$this->model = new NoteModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return NoticeModel
	 * @throws \Exception
	 * 公共模型
	 */
	public function model(){
		return new NoticeModel( Whole::dataInfo() );
	}

	/**
	 * 公告列表
	 */
	public function notice(){
		try{
			$this->model = $this->model();
			$notice = $this->model->noticeList();
			$page = $notice['data']->render();
			return view('notice',[
				'notice' => $notice,
				'page'  =>  $page
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return mixed
	 * 新增公告
	 */
	public function addNotice(){
		try{
			$this->model = $this->model();
			if(Request()->isPost()){
				$data = input('post.');
				$this->model->addNotice( $data );
			}
			return view('addNotice');
		}catch (\Exception $e){
			return json_decode($e->getMessage(),true);
		}
	}

	/**
	 * @return mixed|\think\response\View
	 * 编辑公告
	 */
	public function editNotice(){
		try{
			$this->model = $this->model();
			if(Request()->isPost()){
				$data = input('post.');
				$this->model->editNotice( $data );
				$notice = $this->model->infoNotice( $data['id'] ,'');
			}else{
				$id = input('get.id');
				$notice = $this->model->infoNotice( $id ,'');
			}
			return view('editNotice',[
				'notice'    =>  $notice
			]);
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}

	/**
	 * @return mixed
	 * 上架或下架
	 */
	public function is_show()
	{
		try {
			$this->model = $this->model();
			if(Request()->isGet()){
				$data = input('get.');
				$notice = $this->model->infoNotice( $data['id'],'username' );
				$this->model->is_show( $data ,$notice);
			}
		} catch (\Exception $e) {
			return json_decode($e->getMessage(), true);
		}
	}

	/**
	 * @return mixed
	 * 删除公告
	 */
	public function del(){
		try {
			$this->model = $this->model();
			if(Request()->isGet()){
				$data = input('get.');
				$notice = $this->model->infoNotice( $data['id'],'username' );
				$this->model->del( $data , $notice);
			}
		} catch (\Exception $e) {
			return json_decode($e->getMessage(), true);
		}
	}

}
