<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/2/28
 * Time: 18:04
 */
namespace app\admin\controller;
use app\admin\model\SettingModel;
use app\admin\Traits\Whole;
use think\Controller;
use think\Request;

class Setting extends Controller{
    use Whole{
        isUser as public;
        isOutInsider as public;
    }
    /**
     * @var $model
     */
    protected $model;
    /**
     * @var $data
     * 用户信息
     */
    protected $data;

    /**
     * 实例化模型
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try{
            self::isUser();
            self::isOutInsider();
            $data = Whole::dataInfo();
            $this->model = new SettingModel( $data );
            $this->data = $data;
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }
    public function model(){
        return new SettingModel( Whole::dataInfo() );
    }

    /**
     * @return mixed
     */
    public function index(){
    	try{
		    $data = $this->data;
		    return view('index',[
			    'data' => $data,
		    ]);
	    }catch (\Exception $e){
			$this->error( $e->getMessage() );
	    }
    }
    /**
     * @return mixed
     * 用户登录日志
     */
    public function log(){
    	try{
		    $this->model = $this->model();
		    $logList = $this->model->log();
		    return view('log',[
			    'logList'   =>  $logList,
		    ]);
	    }catch (\Exception $e){
			$this->error( $e->getMessage() );
	    }
    }

	/**
	 * @return mixed
	 * 修改前端显示数量
	 */
    public function set(){
    	try{
			$this->model = $this->model();
			$item = $this->model->item();
			if(Request()->isPost()){
				$data = input('post.');
				$this->model->set( $data );
			}
			return $this->fetch('set',[
				'item'  =>  $item
			]);
	    }catch (\Exception $e){
    		return json_decode($e->getMessage() ,true);
	    }
    }
}