<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/2/26
 * Time: 11:32
 * 热爱曾是唯一的信仰
 */
namespace app\admin\controller;
use app\admin\model\UserModel;
use app\admin\Traits\Whole;
use think\Controller;
use think\Db;
use think\facade\Session;
class User extends Controller{
    /**
     * @var $model
     * 公共模型
     */
    protected $model;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try{
            $this->model = new UserModel();
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }

    public function model(){
        return new UserModel();
    }

    /**
     * @return mixed|\think\response\Json
     * 后台登录
     */
    public function login(){
        try{
            $this->model = $this->model();
            if(Request()->isPost()){
                $data = input('post.');
                $this->model->login($data);
            }
        }catch (\Exception $e){
            return json_decode( $e->getMessage() );
        }
        return view('login');
    }
    /**
     * 退出登录
     */
    public function loginOut(){
        $data = Whole::dataInfo();
        Db::table('user')->where(array('username' => $data['username']))->update(array('state' => '离线'));
        Session::clear('data');
        //清除缓存
        $this->redirect('login');
    }
}