<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/5/14
 * Time: 12:00
 */
namespace app\sadmin\controller;

use app\sadmin\model\CateModel;
use app\sadmin\Traits\Whole;
use think\Controller;

class Cate extends Controller{
	/**
	 * @var $data
	 * 用户资料
	 */
	protected $data;
	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$data = Whole::dataInfo();
			$this->model = new CateModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return CateModel
	 * @throws \Exception
	 */
	public function model(){
		return new CateModel( Whole::dataInfo() );
	}

	/**
	 * @return \think\response\View
	 * 获取分类
	 */
	public function cate(){
		try{
			$this->model = $this->model();
			$tion = $this->model->cate();
			return view('cate',[
				'tion'  =>  $tion
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}
}