<?php
namespace app\index\controller;
use app\index\model\IndexModel;
use app\index\Traits\Whole;
use think\Controller;
use think\Db;
use think\Request;

class Index extends Controller
{
    /**
     * @var int
     * 判断会员状态
     */
    protected $code;
    /**
     * @var $model
     * 公共模型
     */
    protected $model;
    /**
     * @var $data
     * 用户信息
     */
    protected $data;
    use Whole{
        isUser as public;
        isOutInsider as public;
    }

	/**
	 * 初始化
	 */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try{
            self::isUser();
            self::isOutInsider();
            $data = Whole::dataInfo();
            $this->model = new IndexModel( $data );
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }

	/**
	 * @return IndexModel
	 * @throws \Exception
	 */
    public function model(){
    	return new IndexModel( Whole::dataInfo() );
    }
    /**
     * @return mixed
     * 论坛首页
     */
    public function index()
    {
        try{
        	$this->model = $this->model();
            $data = Whole::dataInfo();  //获取用户信息
	        $arr = Whole::Classify();    //获取头部分类
	        $note = "";
	        $tion = "";
	        if(Request()->isPost()){
				$title = input('post.title');
				$note = $this->model->search( $title );
	        }elseif(Request()->isGet()){
		        $tion = input('get.tion');
		        $note = $this->model->index( $tion );
	        }
            $page = $note['note']->render();
            return view('index',[
	            'note'  =>  $note,
	            'data'  =>  $data,
	            'arr'   =>  $arr,
	            'tion'  =>  $tion,
	            'page'  =>  $page
            ]);
        }catch (\Exception $e){
            $this->error( $e->getMessage() );
        }
    }
}
