<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/5/9
 * Time: 11:54
 */
namespace app\index\controller;

use app\index\model\NoticeModel;
use think\Controller;
use app\index\Traits\Whole;
class Notice extends Controller{

	use Whole{
		isUser as public;
		isOutInsider as public;
	}
	/**
	 * @var $data
	 * 用户资料
	 */
	protected $data;

	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			self::isUser();
			self::isOutInsider();
			$data = Whole::dataInfo();
			$this->model = new NoticeModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return NoticeModel
	 * @throws \Exception
	 */
	public function model(){
		return new NoticeModel( Whole::dataInfo() );
	}

	/**
	 * @return \think\response\View
	 * 公告详情
	 */
	public function Notice(){
		try{
			$this->model = $this->model();
			$arr = Whole::Classify();    //获取头部分类
			$id = input('get.id');
			$notice = $this->model->Notice( $id );
			$this->model->num( $id );   //增加阅读人
			return view('notice',[
				'notice'    =>  $notice,
				'arr'   =>  $arr,
				'data'  =>  $this->data
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}
}