<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/4/9
 * Time: 17:35
 */
namespace app\index\controller;

use app\index\model\TaskModel;
use app\index\Traits\Whole;
use think\Controller;
use think\Request;

class Task extends Controller{
	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;
	/**
	 * @var $data
	 * 用户信息
	 */
	protected $data;
	use Whole{
		isUser as public;
		isOutInsider as public;
	}
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			self::isUser();
			self::isOutInsider();
			$data = Whole::dataInfo();
			$this->model = new TaskModel( $data );
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}
	/**
	 * @return TaskModel
	 * @throws \Exception
	 */
	public function model(){
		return new TaskModel( Whole::dataInfo());
	}
	/**
	 * @return \think\response\View
	 * @throws \Exception
	 * 任务页
	 */
	public function index(){
		try{
			$this->model = $this->model();
			$data = Whole::dataInfo();
			$arr = Whole::classify();
			$task = $this->model->task();   //任务完成度
			return view('index',[
				'width'  =>  $task,
				'arr'   =>  $arr,
				'data'  =>  $data,
				'title' =>  '今日任务',
			]);
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}

	}
	public function getLihe(){
		try{
			$this->model = $this->model();
			if(Request()->isGet()){
				$msg = input('get.');
				$this->model->getLihe( $msg );
			}
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}
}