<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/4/17
 * Time: 15:08
 */
namespace app\super\controller;

use app\super\model\AdminModel;
use app\super\Traits\Data;
use think\Controller;
use think\Request;

class Admin extends Controller{
	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;
	/**
	 * @var $data
	 * 用户资料
	 */
	protected $data;

	use Data{
		isUser as public;
	}

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			self::isUser();
			$data = Data::dataInfo();
			$this->model = new AdminModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return AdminModel
	 * @throws \Exception
	 */
	public function model(){
		return new AdminModel( $this->data );
	}

	/**
	 * @return \think\response\View
	 * @throws \Exception
	 * 会员列表
	 */
	public function member_list(){
		$this->model = $this->model();
		$admin = $this->model->member_list();
		$page = $admin['data']->render();
		return view('member_list',[
			'page'  =>  $page,
			'admin' =>  $admin
		]);
	}
	/**
	 * @return mixed|\think\response\View
	 * 增加会员
	 */
	public function member_add(){
		try{
			$this->model = $this->model();
			if(Request()->isPost()){
				$data = input('post.');
				$data['date'] = time();
				$data['insider'] = '普通用户';
				$data['exp']    =   0;
				$data['target'] = 60;
				$data['lv'] =   0;
				$this->model->member_add( $data );
			}
			return view('member_add');
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}

	public function member_edit(){
		try{
			$this->model = $this->model();
			if(Request()->isPost()){
				$data = input('post.');
				$this->model->member_edit( $data );
			}
			$id = input('get.id');
			$Admin = $this->model->adminInfo( $id );
			return view('member_edit',[
				'admin' =>  $Admin
			]);
		}catch (\Exception $e){
			return json_decode( $e->getMessage() , true);
		}
	}

	public function member_del(){
		return view('member_del');
	}

	/**
	 * @return mixed|\think\response\View
	 * 修改会员密码
	 */
	public function member_password(){
		try{
			$this->model = $this->model();
			if(Request()->isPost()){
				$data = input('post.');
				$this->model->member_password( $data );
			}
			$id = input('get.id');
			$Admin = $this->model->adminInfo( $id );
			return view('member_password',[
				'admin' =>  $Admin
			]);
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}
	public function stop(){
		try{
			$this->model = $this->model();
			$data = input('post.');
			$this->model->stop( $data );
		}catch (\Exception $e){
			return json_decode( $e->getMessage() ,true);
		}
	}
}