<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/4/24
 * Time: 14:49
 */
namespace app\super\controller;

use app\super\model\OrderModel;
use think\Controller;
use app\super\Traits\Data;
class Order extends Controller{
	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;
	/**
	 * @var $data
	 * 用户资料
	 */
	protected $data;

	use Data{
		isUser as public;
	}

	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		self::isUser();
		try{
			$data = Data::dataInfo();
			$this->model = new OrderModel( $data );
			$this->data = $data;
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return OrderModel
	 * @throws \Exception
	 */
	public function model(){
		return new OrderModel( Data::dataInfo() );
	}

	public function order_list(){
		try{
			return view('order_list');
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	public function order_add(){
		try{
			return view('order_add');
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}
}