<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/4/16
 * Time: 15:43
 */
namespace app\super\controller;

use app\super\Model\UserModel;
use think\Controller;
use think\Request;

class User extends Controller{
	/**
	 * @var $model
	 * 公共模型
	 */
	protected $model;

	/**
	 * 初始化
	 */
	public function initialize()
	{
		parent::initialize(); // TODO: Change the autogenerated stub
		try{
			$this->model = new UserModel();
		}catch (\Exception $e){
			$this->error( $e->getMessage() );
		}
	}

	/**
	 * @return UserModel
	 */
	public function model(){
		return new UserModel();
	}

	/**
	 * @return mixed|\think\response\View
	 * 登录
	 */
	public function login(){
		$this->model = $this->model();
		try{
			if(Request()->isPost()){
				$msg = input('post.');
				$this->model->login( $msg );
			}
			return view('login');
		}catch (\Exception $e){
			return json_decode($e->getMessage() ,true);
		}
	}
}